apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  releaseName: flagger
  targetNamespace: linkerd
  chart:
    spec:
      valuesFile: ./flagger.values.yaml
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
  install: {}
  interval: 1m0s
