apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chartmuseum
  namespace: flux-system
spec:
  releaseName: chartmuseum
  targetNamespace: chartmuseum
  storageNamespace: chartmuseum
  chart:
    spec:
      chart: chartmuseum
      version: 0.13.1
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
  values:
    pv:
      enabled: true
      pvname: chartmuseum
      capacity:
        storage: 8Gi
      accessMode: ReadWriteOnce
      nfs:
        server: 192.168.1.60
        path: /mnt/disk1/charts
    env:
      open:
        # storage backend, can be one of: local, alibaba, amazon, google, microsoft, oracle
        STORAGE: local
        # STORAGE_LOCAL_ROOTDIR: /charts
  install:
    createNamespace: true
  interval: 1m0s
