apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.1.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    installCRDs: true
  install: {}
  interval: 1m0s