apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging1
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: alex.bechmann@outlook.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx