apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  releaseName: nfs-subdir-external-provisioner
  targetNamespace: nfs
  storageNamespace: nfs
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.10
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  values:
    nfs:
      server: 192.168.2.30
      path: /DataE/Raspberry/k8sdata
    storageClass:
      name: s1-k8sdata
  install:
    createNamespace: true
  interval: 1m0s
