apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  releaseName: nginx-ingress
  targetNamespace: nginx-ingress
  storageNamespace: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: 3.15.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  values:
    loadBalancerIP: 192.168.1.20
    controller:
      podAnnotations:
        linkerd.io/inject: enabled
      replicaCount: 2
  install:
    createNamespace: true
  interval: 10m0s
