apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  releaseName: flagger
  targetNamespace: linkerd
  storageNamespace: linkerd
  chart:
    spec:
      chart: flagger
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: flagger
  values:
    # crd:
    #   create: false
    meshProvider: linkerd
    metricsServer: http://linkerd-prometheus:9090
  install:
    createNamespace: true
  interval: 1m0s
